# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'    

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial (d85d014d-f26a-4dc7-be57-8b31b72b3247)'
    subscriptionId: 'd85d014d-f26a-4dc7-be57-8b31b72b3247'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'db2'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/anuragsharma21-github/AzureDevOPs/blob/main/rhelvm_db2.json'
    csmParametersFileLink: 'https://github.com/anuragsharma21-github/AzureDevOPs/blob/main/parameter.json'
    deploymentMode: 'Incremental'